# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-27 16:58
from __future__ import unicode_literals

from django.db import migrations


def reverse_selection(apps, schema_editor):
    MaintenanceRecord = apps.get_model("api", "MaintenanceRecord")
    all_records = MaintenanceRecord.objects.all()
    for record in all_records:
        record.disable_login = not record.disable_login
        record.save()

def go_back(apps, schema_editor):
    return

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_maintenancenotice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerecord',
            old_name='allow_login',
            new_name='disable_login',
        ),
        migrations.RunPython(reverse_selection, go_back)
    ]
